apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: zomato-deployment
spec:
  selector:
    matchLabels:
      app: zomato
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: zomato
    spec:
      containers:
        - name: zomato
          image: rajeshdondapati309/nojs-app1:v1 # Image that will be used to containers in the cluster
          imagePullPolicy: Always
          ports:
            - containerPort: 3000 # The port that the container is running on in the cluster


---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: zomato-ssvc
spec:
  selector:
    app: zomato
  ports:
    - protocol: "TCP"
      port: 3000
      targetPort: 3000
  type: LoadBalancer # type of the service.
